os:
  - linux
dist: trusty
language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
        - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
jobs:
  include:
    - stage: build
      script: scripts/1_setup_jmc.sh
    - stage: uitests
      script: scripts/2_run_ui_tests.sh
